export const categories = [
	{
		imageUrl: "/images/ikoni_koulu.svg",
		name: "Aikuinen ja lapsi puisto",
		subCategory: [
			{ subName: "Paritemppuili",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Pariakrobatia Easy",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Sohvatemput",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Hassuttelun nousut ja laskut",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Tempuilut vesimukilla",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Combat Tanssi",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Geegon Hyppytreenit",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Paritemppuili",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Paritemppuili",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
		],
	},
	{
		imageUrl: "/images/ikoni_koulu.svg",
		name:"Akrobatian kirjasto",
		subCategory: [
			{ subName: "Paritemppuili",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Pariakrobatia Easy",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Sohvatemput",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Hassuttelun nousut ja laskut",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Tempuilut vesimukilla",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Combat Tanssi",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Geegon Hyppytreenit",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Paritemppuili",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Paritemppuili",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
		]
	},
	{
		imageUrl: "/images/ikoni_koulu.svg",
		name:"Hassuttelun satama",
		subCategory: [
			{ subName: "Paritemppuili",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Pariakrobatia Easy",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Sohvatemput",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Hassuttelun nousut ja laskut",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Tempuilut vesimukilla",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Combat Tanssi",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Geegon Hyppytreenit",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Paritemppuili",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Paritemppuili",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
		]
	},
	{
		imageUrl: "/images/ikoni_koulu.svg",
		name:"Hyppimisen Plaza",
		subCategory: [
			{ subName: "Paritemppuili",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Pariakrobatia Easy",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Sohvatemput",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Hassuttelun nousut ja laskut",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Tempuilut vesimukilla",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Combat Tanssi",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Geegon Hyppytreenit",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Paritemppuili",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Paritemppuili",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
		]
	},
	{
		imageUrl: "/images/ikoni_koulu.svg",
		name:"Hyppynarun ja vanteen katu",
		subCategory: [
			{ subName: "Paritemppuili",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Pariakrobatia Easy",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Sohvatemput",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Hassuttelun nousut ja laskut",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Tempuilut vesimukilla",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Combat Tanssi",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Geegon Hyppytreenit",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Paritemppuili",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Paritemppuili",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
		]
	},
	{
		imageUrl: "/images/ikoni_koulu.svg",
		name:"Kaverusten huvipuisto",
		subCategory: [
			{ subName: "Paritemppuili",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Pariakrobatia Easy",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Sohvatemput",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Hassuttelun nousut ja laskut",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Tempuilut vesimukilla",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Combat Tanssi",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Geegon Hyppytreenit",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Paritemppuili",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
			{ subName: "Paritemppuili",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
			},
		]
	},
	
];