export const categories = [
	{
		id: "1",
		imageUrl: "/images/ikoni_koulu.svg",
		name: "Aikuinen-ja-lapsi-puisto",
		subCategory: [
			{ id: "15",
				subName: "Paritemppuili",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
				task: [
					{ 
						id: "155",
						taskName: "Ilmakuperkekka",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
						taskVideo: "/videos/logo_white.mp4",
					},
					{ 
						id: "156",
						taskName: "Nosto-ympäri",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
						taskVideo: "/videos/logo_white.mp4",
					},
				]
			},
			{ id: "16",
				subName: "Pariakrobatia-Easy",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
				task: [
					{ 
						id: "166",
						taskName: "Polvelle-nousu",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
						taskVideo: "/videos/logo_white.mp4",
					},
					{ 
						id: "167",
						taskName: "Ilmakuperkekka",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
						taskVideo: "/videos/logo_white.mp4",
					},
					{ 
						id: "168",
						taskName: "Nosto-ympäri",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
						taskVideo: "/videos/logo_white.mp4",
					},
				]
			},
		],
	},
	{
		id: "12",
		imageUrl: "/images/ikoni_koulu.svg",
		name:"Akrobatian-kirjasto",
		subCategory: [
			{ id: "14",
				subName: "Sohvatemput",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
				task: [
					{ 
						id: "144",
						taskName: "Etuperin-kuperkeikka",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
					},
					{ 
						id: "145",
						taskName: "Käsiseisonta",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
					},
					{ 
						id: "146",
						taskName: "Sohvan-yli-voitti",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
					},
					{ id: "147",
						taskName: "Käsitasapaino-peppu-ylös",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
					},
					{ id: "148",
						taskName: "Parkour-hyppy",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
					},
					{ id: "149",
						taskName: "Kieriminen-sohvalla",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
					},
				]
					
			},
			{ id: "11",
				subName: "Combat-Tanssi",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
				task: [
					{ id: "111",
						taskName: "Päänpäällä",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
						taskVideo: "/videos/logo_white.mp4",
					},
					{ id: "112",
						taskName: "Veden-Kaato",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
						taskVideo: "/videos/logo_white.mp4",
					},
					{ id: "113",
						taskName: "Selkä-selkää-vasten",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
						taskVideo: "/videos/logo_white.mp4",
					},
					{ id: "114",
						taskName: "Lontoonbussi",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
						taskVideo: "/videos/logo_white.mp4",
					},
					{ id: "115",
						taskName: "Lontoonbussi-seisoen",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
						taskVideo: "/videos/logo_white.mp4",
					},
					{ id: "116",
						taskName: "Lentokone",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
						taskVideo: "/videos/logo_white.mp4",
					},
					{ id: "117",
						taskName: "Rapupyramidi",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
						taskVideo: "/videos/logo_white.mp4",
					},
					{ id: "118",
						taskName: "Neliö",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
						taskVideo: "/videos/logo_white.mp4",
					},
					{ id: "119",
						taskName: "Kuperkeikkaheitto",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
						taskVideo: "/videos/logo_white.mp4",
					},
					{ id: "190",
						taskName: "Polvelle nousu",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
						taskVideo: "/videos/logo_white.mp4",
					},
					{ id: "120",
						taskName: "Ilmakuperkekka",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
						taskVideo: "/videos/logo_white.mp4",
					},
					{ id: "121",
						taskName: "Nosto-ympäri",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
						taskVideo: "/videos/logo_white.mp4",
					},
				]
			},
		]
	},
];