export const categories = [
	{
		imageUrl: "/images/ikoni_koulu.svg",
		name: "Aikuinen ja lapsi puisto",
		subCategory: [
			{ subName: "Paritemppuili",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
				task: [
					{ taskName: "Hippa",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
						taskVideo: "/videos/logo_white.mp4",
					},
					{ taskName: "Yli ja Ali",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
						taskVideo: "/videos/logo_white.mp4",
					},
				]
			},
			{ subName: "Pariakrobatia Easy",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
				task: [
					{ taskName: "Selkä selkää vasten",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
						taskVideo: "/videos/logo_white.mp4",
					},
					{ taskName: "Lontoonbussi",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
						taskVideo: "/videos/logo_white.mp4",
					},
				]
			},
		],
	},
	{
		imageUrl: "/images/ikoni_koulu.svg",
		name:"Akrobatian kirjasto",
		subCategory: [
			{ subName: "Sohvatemput",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
				task: 
					{ taskName: "Etuperin kuperkeikka",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
					},
			},
		]
	},
	{
		imageUrl: "/images/ikoni_koulu.svg",
		name:"Hassuttelun satama",
		subCategory: [
			{ subName: "Hessuttelun nousut ja laskut",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
				task: [
					{ taskName: "Alas polvilleen",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
					},
					{ taskName: "Istumaan",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
					},
				]
			},
			{ subName: "Temppuilut Vesimukilla",
				imageDesc: "/images/ikoni_koulu.svg",
				width: 120,
    		height: 120,
				task: [
					{ taskName: "Pään päällä",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
					},
					{ taskName: "Veden Kaato",
						imageTask: "/images/ikoni_koulu.svg",
						width: 120,
    				height: 120,
					},
				]
			},
		]
	},
];